### ISSUE TITLE
package name mismatch

### ISSUE THREAD

**Issue by wonjoonSeol-WS** [MousaZeidBaker/poetryup#10]
I stumbled upon this repo while looking at this issue: https://github.com/python-poetry/poetry/issues/461

poetryup currently has a issue with a package name that contains capital letters:

For instance, try adding these following packages on poetry and run your command
```
poetry add types-pyyaml
poetry add pyjwt 
```

You would end up with the following log message:
```
INFO:root:Bumping skipped for dependency named: pyjwt
INFO:root:Bumping skipped for dependency named: types-pyyaml
```

This is due to the fact that you are assuming on `poetry show --tree` command would return the same package name.

This assumption is false, poetry show command always return lowercase package name whereas the pyproject contains the capital letter:

```
types-PyYAML
pyJWT 
```

Since you are completely relying on tomlkit to parse the file, the easiest fix would be to first convert all package name into lowercase string and then run the command. But changing package name in this manner makes unnecessary edits the pyproject.toml file. 

Alternatively you could:
(1) parse toml file yourself to avoid this issue all together OR
(2) make a mapper that maps pyproject package name to poetry show package name 

I was going to submit a PR instead of creating this issue but seems like all we need to do here to update the package is to have a simple script that gets the package name and do poetry add package_name@latest? So I will just make separate script instead.

Some other issues I found:
- the regex should also contain - character 
- your filename is identical to the directory name, this is considered a bad practice (https://docs.python.org/2/tutorial/modules.html#the-module-search-path)
- poetry update should be called after updating pyproject.toml not before?

**Comment by MousaZeidBaker** [comment]
@wonjoonSeol-WS FYI: `poetryup` can now update all dependencies to their LATEST available version by setting a flag as following `poetryup --latest`
