### ISSUE TITLE
Downgrading pre-release versions

### ISSUE THREAD

**Issue by Elendiar** [MousaZeidBaker/poetryup#53]
Hi, find this usefull package, but notice some issue with downgrading pre-release versions:
`python-telegram-bot = "20.0a1"`
_Updating python-telegram-bot (20.0a1 -> 13.12)_
Its not a big problem anyway, but maybe you might be interested.

**Comment by Elendiar** [comment]
Poetry: **1.2.0b2**
Poetryup: **0.9.0**

Running **poetryup --latest**, still downgraded:
_toml:_
`python-telegram-bot = "20.0a2"`
_log:_
```
Package operations: 0 installs, 4 updates, 6 removals

  • Removing anyio (3.6.1)
  • Removing h11 (0.12.0)
  • Removing httpcore (0.15.0)
  • Removing httpx (0.23.0)
  • Removing rfc3986 (1.5.0)
  • Removing sniffio (1.2.0)
  • Updating apscheduler (3.9.1 -> 3.6.3)
  • Updating cachetools (5.2.0 -> 4.2.2)
  • Updating python-telegram-bot (20.0a2 -> 13.12)
  • Updating redis (4.3.3 -> 4.3.4)
```

**Comment by MousaZeidBaker** [comment]
`poetryup` have been migrated to [poetry-plugin-up](https://github.com/MousaZeidBaker/poetry-plugin-up) and if I am not mistaken, it should now handle pre-releases. I strongly recommend using the plugin since this repo will be deprecated.
