### ISSUE TITLE
Skip install

### ISSUE THREAD

**Issue by meabed** [MousaZeidBaker/poetryup#71]
Thank you for making this! extremely helpful.

Is there an option to skip installation, I just want to update the project and lock file without installing all deps?

Thank you!

**Comment by MousaZeidBaker** [comment]
Glad you like it. Unfortunately there is no option to skip installation since `poetryup` parses the lock file to determine new versions so packages must be installed.

**Comment by meabed** [comment]
like this I am using for requirement and doesn't install just update ( through the API ): https://pypi.org/project/pip-check-updates/
